name: srag
version: "1.0.0"
profile: srag

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  srag:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
